//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duality.Editor.Plugins.Tilemaps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TilemapsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TilemapsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duality.Editor.Plugins.Tilemaps.Properties.TilemapsRes", typeof(TilemapsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a user dialog that allows to resize the selected Tilemaps..
        /// </summary>
        internal static string ActionDesc_ResizeTilemap {
            get {
                return ResourceManager.GetString("ActionDesc_ResizeTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Tilemap.
        /// </summary>
        internal static string ActionName_ResizeTilemap {
            get {
                return ResourceManager.GetString("ActionName_ResizeTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the arrow keys to quickly change tilemap selection..
        /// </summary>
        internal static string CamView_Help_TilemapEditor_SelectTilemaps {
            get {
                return ResourceManager.GetString("CamView_Help_TilemapEditor_SelectTilemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilemap Editor Actions.
        /// </summary>
        internal static string CamView_Help_TilemapEditorActions {
            get {
                return ResourceManager.GetString("CamView_Help_TilemapEditorActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorPick {
            get {
                object obj = ResourceManager.GetObject("CursorPick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileBrush {
            get {
                object obj = ResourceManager.GetObject("CursorTileBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileFill {
            get {
                object obj = ResourceManager.GetObject("CursorTileFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileOval {
            get {
                object obj = ResourceManager.GetObject("CursorTileOval", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileRect {
            get {
                object obj = ResourceManager.GetObject("CursorTileRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconPick {
            get {
                object obj = ResourceManager.GetObject("IconPick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconResize {
            get {
                object obj = ResourceManager.GetObject("IconResize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileBrush {
            get {
                object obj = ResourceManager.GetObject("IconTileBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileFill {
            get {
                object obj = ResourceManager.GetObject("IconTileFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileOval {
            get {
                object obj = ResourceManager.GetObject("IconTileOval", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilePalette {
            get {
                object obj = ResourceManager.GetObject("IconTilePalette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileRect {
            get {
                object obj = ResourceManager.GetObject("IconTileRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileSelect {
            get {
                object obj = ResourceManager.GetObject("IconTileSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Picker.
        /// </summary>
        internal static string ItemName_Pick {
            get {
                return ResourceManager.GetString("ItemName_Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Brush.
        /// </summary>
        internal static string ItemName_TileBrush {
            get {
                return ResourceManager.GetString("ItemName_TileBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Fill.
        /// </summary>
        internal static string ItemName_TileFill {
            get {
                return ResourceManager.GetString("ItemName_TileFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Oval.
        /// </summary>
        internal static string ItemName_TileOval {
            get {
                return ResourceManager.GetString("ItemName_TileOval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Rect.
        /// </summary>
        internal static string ItemName_TileRect {
            get {
                return ResourceManager.GetString("ItemName_TileRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Tool.
        /// </summary>
        internal static string ItemName_TileSelect {
            get {
                return ResourceManager.GetString("ItemName_TileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Palette.
        /// </summary>
        internal static string MenuItemName_TilePalette {
            get {
                return ResourceManager.GetString("MenuItemName_TilePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing the selected Tilemaps will preserve the part of their content that still fits the new size and origin..
        /// </summary>
        internal static string TilemapSetupHeader_ResizeMap {
            get {
                return ResourceManager.GetString("TilemapSetupHeader_ResizeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize {0} Tilemaps.
        /// </summary>
        internal static string TilemapSetupHeader_ResizeMultipleTilemaps {
            get {
                return ResourceManager.GetString("TilemapSetupHeader_ResizeMultipleTilemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize &apos;{0}&apos;.
        /// </summary>
        internal static string TilemapSetupHeader_ResizeSingleTilemap {
            get {
                return ResourceManager.GetString("TilemapSetupHeader_ResizeSingleTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tileset selected.
        /// </summary>
        internal static string TilePalette_NoTilesetSelected {
            get {
                return ResourceManager.GetString("TilePalette_NoTilesetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset: {0}.
        /// </summary>
        internal static string TilePalette_SelectedTileset {
            get {
                return ResourceManager.GetString("TilePalette_SelectedTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Tiles.
        /// </summary>
        internal static string UndoRedo_EditTilemapDrawTiles {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapDrawTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Tile Oval.
        /// </summary>
        internal static string UndoRedo_EditTilemapFillTileOval {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapFillTileOval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Tile Rect.
        /// </summary>
        internal static string UndoRedo_EditTilemapFillTileRect {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapFillTileRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Fill Tiles.
        /// </summary>
        internal static string UndoRedo_EditTilemapFloodFillTiles {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapFloodFillTiles", resourceCulture);
            }
        }
    }
}
