//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duality.Editor.Plugins.Tilemaps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TilemapsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TilemapsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duality.Editor.Plugins.Tilemaps.Properties.TilemapsRes", typeof(TilemapsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Tileset Resource based on the Pixmap..
        /// </summary>
        internal static string ActionDesc_CreateTileset {
            get {
                return ResourceManager.GetString("ActionDesc_CreateTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a Camera View in Tilemap Editor mode and selects the Tilemap for editing..
        /// </summary>
        internal static string ActionDesc_OpenTilemapEditor {
            get {
                return ResourceManager.GetString("ActionDesc_OpenTilemapEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Tileset for editing..
        /// </summary>
        internal static string ActionDesc_OpenTileset {
            get {
                return ResourceManager.GetString("ActionDesc_OpenTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a user dialog that allows to resize the selected Tilemaps. If no tilemaps are selected, it will resize all currently active, non-hidden tilemaps in the current scene..
        /// </summary>
        internal static string ActionDesc_ResizeTilemap {
            get {
                return ResourceManager.GetString("ActionDesc_ResizeTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a user dialog that helps you quickly create a set of layered Tilemaps..
        /// </summary>
        internal static string ActionDesc_SetupTilemap {
            get {
                return ResourceManager.GetString("ActionDesc_SetupTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tileset.
        /// </summary>
        internal static string ActionName_CreateTileset {
            get {
                return ResourceManager.GetString("ActionName_CreateTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tilemap Editor.
        /// </summary>
        internal static string ActionName_OpenTilemapEditor {
            get {
                return ResourceManager.GetString("ActionName_OpenTilemapEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tileset.
        /// </summary>
        internal static string ActionName_OpenTileset {
            get {
                return ResourceManager.GetString("ActionName_OpenTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Tilemap.
        /// </summary>
        internal static string ActionName_ResizeTilemap {
            get {
                return ResourceManager.GetString("ActionName_ResizeTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Tilemaps.
        /// </summary>
        internal static string ActionName_SetupTilemap {
            get {
                return ResourceManager.GetString("ActionName_SetupTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the arrow keys to quickly change tilemap selection..
        /// </summary>
        internal static string CamView_Help_TilemapEditor_SelectTilemaps {
            get {
                return ResourceManager.GetString("CamView_Help_TilemapEditor_SelectTilemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilemap Editor Actions.
        /// </summary>
        internal static string CamView_Help_TilemapEditorActions {
            get {
                return ResourceManager.GetString("CamView_Help_TilemapEditorActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilemap Editor.
        /// </summary>
        internal static string CamViewState_TilemapEditor_Name {
            get {
                return ResourceManager.GetString("CamViewState_TilemapEditor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorPick {
            get {
                object obj = ResourceManager.GetObject("CursorPick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileBrush {
            get {
                object obj = ResourceManager.GetObject("CursorTileBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileFill {
            get {
                object obj = ResourceManager.GetObject("CursorTileFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileOval {
            get {
                object obj = ResourceManager.GetObject("CursorTileOval", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CursorTileRect {
            get {
                object obj = ResourceManager.GetObject("CursorTileRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconPick {
            get {
                object obj = ResourceManager.GetObject("IconPick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconResize {
            get {
                object obj = ResourceManager.GetObject("IconResize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconSetup {
            get {
                object obj = ResourceManager.GetObject("IconSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileBrush {
            get {
                object obj = ResourceManager.GetObject("IconTileBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileFill {
            get {
                object obj = ResourceManager.GetObject("IconTileFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileOval {
            get {
                object obj = ResourceManager.GetObject("IconTileOval", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilePalette {
            get {
                object obj = ResourceManager.GetObject("IconTilePalette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileRect {
            get {
                object obj = ResourceManager.GetObject("IconTileRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTileSelect {
            get {
                object obj = ResourceManager.GetObject("IconTileSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetCollisionInfo {
            get {
                object obj = ResourceManager.GetObject("IconTilesetCollisionInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetCollisionLayer {
            get {
                object obj = ResourceManager.GetObject("IconTilesetCollisionLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetDepthFlatTile {
            get {
                object obj = ResourceManager.GetObject("IconTilesetDepthFlatTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetDepthInfo {
            get {
                object obj = ResourceManager.GetObject("IconTilesetDepthInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetDepthLayer {
            get {
                object obj = ResourceManager.GetObject("IconTilesetDepthLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetDepthVertical {
            get {
                object obj = ResourceManager.GetObject("IconTilesetDepthVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetDepthVerticalTile {
            get {
                object obj = ResourceManager.GetObject("IconTilesetDepthVerticalTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetEditor {
            get {
                object obj = ResourceManager.GetObject("IconTilesetEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetSingleVisualLayer {
            get {
                object obj = ResourceManager.GetObject("IconTilesetSingleVisualLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconTilesetVisualLayers {
            get {
                object obj = ResourceManager.GetObject("IconTilesetVisualLayers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Picker.
        /// </summary>
        internal static string ItemName_Pick {
            get {
                return ResourceManager.GetString("ItemName_Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Brush.
        /// </summary>
        internal static string ItemName_TileBrush {
            get {
                return ResourceManager.GetString("ItemName_TileBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Fill.
        /// </summary>
        internal static string ItemName_TileFill {
            get {
                return ResourceManager.GetString("ItemName_TileFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Oval.
        /// </summary>
        internal static string ItemName_TileOval {
            get {
                return ResourceManager.GetString("ItemName_TileOval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Rect.
        /// </summary>
        internal static string ItemName_TileRect {
            get {
                return ResourceManager.GetString("ItemName_TileRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Tool.
        /// </summary>
        internal static string ItemName_TileSelect {
            get {
                return ResourceManager.GetString("ItemName_TileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Palette.
        /// </summary>
        internal static string MenuItemName_TilePalette {
            get {
                return ResourceManager.GetString("MenuItemName_TilePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset Editor.
        /// </summary>
        internal static string MenuItemName_TilesetEditor {
            get {
                return ResourceManager.GetString("MenuItemName_TilesetEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset modified.
        /// </summary>
        internal static string Msg_ApplyOrResetTilesetChanges_Caption {
            get {
                return ResourceManager.GetString("Msg_ApplyOrResetTilesetChanges_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve made changes to Tileset &apos;{0}&apos;. Do you want to Apply them?.
        /// </summary>
        internal static string Msg_ApplyOrResetTilesetChanges_Text {
            get {
                return ResourceManager.GetString("Msg_ApplyOrResetTilesetChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize {0} Tilemaps.
        /// </summary>
        internal static string TilemapSetupHeader_ResizeMultipleTilemaps {
            get {
                return ResourceManager.GetString("TilemapSetupHeader_ResizeMultipleTilemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize &apos;{0}&apos;.
        /// </summary>
        internal static string TilemapSetupHeader_ResizeSingleTilemap {
            get {
                return ResourceManager.GetString("TilemapSetupHeader_ResizeSingleTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tileset available.
        /// </summary>
        internal static string TilePalette_NoTilesetSelected {
            get {
                return ResourceManager.GetString("TilePalette_NoTilesetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset: {0}.
        /// </summary>
        internal static string TilePalette_SelectedTileset {
            get {
                return ResourceManager.GetString("TilePalette_SelectedTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TilesetCollisionBit {
            get {
                object obj = ResourceManager.GetObject("TilesetCollisionBit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TilesetCollisionDiagDown {
            get {
                object obj = ResourceManager.GetObject("TilesetCollisionDiagDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TilesetCollisionDiagUp {
            get {
                object obj = ResourceManager.GetObject("TilesetCollisionDiagUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TilesetCollisionHorizontal {
            get {
                object obj = ResourceManager.GetObject("TilesetCollisionHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TilesetCollisionVertical {
            get {
                object obj = ResourceManager.GetObject("TilesetCollisionVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tileset selected.
        /// </summary>
        internal static string TilesetEditor_NoTilesetSelected {
            get {
                return ResourceManager.GetString("TilesetEditor_NoTilesetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tileset: {0}.
        /// </summary>
        internal static string TilesetEditor_SelectedTileset {
            get {
                return ResourceManager.GetString("TilesetEditor_SelectedTileset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aux. Collision.
        /// </summary>
        internal static string TilesetEditorCollisionAuxLayer_Name {
            get {
                return ResourceManager.GetString("TilesetEditorCollisionAuxLayer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Index {0}.
        /// </summary>
        internal static string TilesetEditorCollisionLayer_Desc {
            get {
                return ResourceManager.GetString("TilesetEditorCollisionLayer_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Collision.
        /// </summary>
        internal static string TilesetEditorCollisionMainLayer_Name {
            get {
                return ResourceManager.GetString("TilesetEditorCollisionMainLayer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Rendering Order.
        /// </summary>
        internal static string TilesetEditorDepthOffset_Desc {
            get {
                return ResourceManager.GetString("TilesetEditorDepthOffset_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Offset.
        /// </summary>
        internal static string TilesetEditorDepthOffset_Name {
            get {
                return ResourceManager.GetString("TilesetEditorDepthOffset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical / Flat Tiles.
        /// </summary>
        internal static string TilesetEditorDepthVertical_Desc {
            get {
                return ResourceManager.GetString("TilesetEditorDepthVertical_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string TilesetEditorDepthVertical_Name {
            get {
                return ResourceManager.GetString("TilesetEditorDepthVertical_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision Info.
        /// </summary>
        internal static string TilesetEditorMode_CollisionInfo_Name {
            get {
                return ResourceManager.GetString("TilesetEditorMode_CollisionInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Info.
        /// </summary>
        internal static string TilesetEditorMode_DepthInfo_Name {
            get {
                return ResourceManager.GetString("TilesetEditorMode_DepthInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Layers.
        /// </summary>
        internal static string TilesetEditorMode_VisualLayer_Name {
            get {
                return ResourceManager.GetString("TilesetEditorMode_VisualLayer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Tileset Changes.
        /// </summary>
        internal static string UndoRedo_ApplyTilesetChanges {
            get {
                return ResourceManager.GetString("UndoRedo_ApplyTilesetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Tiles.
        /// </summary>
        internal static string UndoRedo_EditTilemapDrawTiles {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapDrawTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Tile Oval.
        /// </summary>
        internal static string UndoRedo_EditTilemapFillTileOval {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapFillTileOval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Tile Rect.
        /// </summary>
        internal static string UndoRedo_EditTilemapFillTileRect {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapFillTileRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Fill Tiles.
        /// </summary>
        internal static string UndoRedo_EditTilemapFloodFillTiles {
            get {
                return ResourceManager.GetString("UndoRedo_EditTilemapFloodFillTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Tilemap.
        /// </summary>
        internal static string UndoRedo_ResizeTilemap {
            get {
                return ResourceManager.GetString("UndoRedo_ResizeTilemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Tileset Changes.
        /// </summary>
        internal static string UndoRedo_RevertTilesetChanges {
            get {
                return ResourceManager.GetString("UndoRedo_RevertTilesetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Visual Layer.
        /// </summary>
        internal static string UndoRedo_TilesetAddVisualLayer {
            get {
                return ResourceManager.GetString("UndoRedo_TilesetAddVisualLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tile Input.
        /// </summary>
        internal static string UndoRedo_TilesetEditTileInput {
            get {
                return ResourceManager.GetString("UndoRedo_TilesetEditTileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Visual Layer.
        /// </summary>
        internal static string UndoRedo_TilesetRemoveVisualLayer {
            get {
                return ResourceManager.GetString("UndoRedo_TilesetRemoveVisualLayer", resourceCulture);
            }
        }
    }
}
