//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duality.Editor.Plugins.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorBaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorBaseRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duality.Editor.Plugins.Base.Properties.EditorBaseRes", typeof(EditorBaseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new Material Resource based on the Texture. ähnelt.
        /// </summary>
        public static string ActionDesc_CreateMaterial {
            get {
                return ResourceManager.GetString("ActionDesc_CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new ShaderProgram Resource based on Vertex- and Fragmentshaders. ähnelt.
        /// </summary>
        public static string ActionDesc_CreateShaderProgram {
            get {
                return ResourceManager.GetString("ActionDesc_CreateShaderProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new Sound Resource based on the AudioData. ähnelt.
        /// </summary>
        public static string ActionDesc_CreateSound {
            get {
                return ResourceManager.GetString("ActionDesc_CreateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new Texture Resource based on the Pixmap. ähnelt.
        /// </summary>
        public static string ActionDesc_CreateTexture {
            get {
                return ResourceManager.GetString("ActionDesc_CreateTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus Camera on GameObject. ähnelt.
        /// </summary>
        public static string ActionDesc_FocusGameObject {
            get {
                return ResourceManager.GetString("ActionDesc_FocusGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a GameObject by instantiating the Prefab. ähnelt.
        /// </summary>
        public static string ActionDesc_InstantiatePrefab {
            get {
                return ResourceManager.GetString("ActionDesc_InstantiatePrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Resource in external editor. ähnelt.
        /// </summary>
        public static string ActionDesc_OpenResourceExternal {
            get {
                return ResourceManager.GetString("ActionDesc_OpenResourceExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the Scene. ähnelt.
        /// </summary>
        public static string ActionDesc_OpenScene {
            get {
                return ResourceManager.GetString("ActionDesc_OpenScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Material ähnelt.
        /// </summary>
        public static string ActionName_CreateMaterial {
            get {
                return ResourceManager.GetString("ActionName_CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ShaderProgram ähnelt.
        /// </summary>
        public static string ActionName_CreateShaderProgram {
            get {
                return ResourceManager.GetString("ActionName_CreateShaderProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Sound ähnelt.
        /// </summary>
        public static string ActionName_CreateSound {
            get {
                return ResourceManager.GetString("ActionName_CreateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Texture ähnelt.
        /// </summary>
        public static string ActionName_CreateTexture {
            get {
                return ResourceManager.GetString("ActionName_CreateTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DropdownSettingsBlack {
            get {
                object obj = ResourceManager.GetObject("DropdownSettingsBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconAbortCross {
            get {
                object obj = ResourceManager.GetObject("IconAbortCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        public static System.Drawing.Icon IconEye {
            get {
                object obj = ResourceManager.GetObject("IconEye", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconSpeakerBlack {
            get {
                object obj = ResourceManager.GetObject("IconSpeakerBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconSpeakerWhite {
            get {
                object obj = ResourceManager.GetObject("IconSpeakerWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t remove {0} because it is required by the &apos;{1}&apos; Component. ähnelt.
        /// </summary>
        public static string MenuItemDesc_CantRemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemDesc_CantRemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application Data ähnelt.
        /// </summary>
        public static string MenuItemName_AppData {
            get {
                return ResourceManager.GetString("MenuItemName_AppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string MenuItemName_RemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemName_RemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string MenuItemName_ResetComponent {
            get {
                return ResourceManager.GetString("MenuItemName_ResetComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default User Data ähnelt.
        /// </summary>
        public static string MenuItemName_UserData {
            get {
                return ResourceManager.GetString("MenuItemName_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a joint type and click the add button to add a new joint to the Collider ähnelt.
        /// </summary>
        public static string PropertyDesc_AddJoint {
            get {
                return ResourceManager.GetString("PropertyDesc_AddJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The joints second Collider, i.e. the one that is connected to this one using the joint. ähnelt.
        /// </summary>
        public static string PropertyDesc_OtherCollider {
            get {
                return ResourceManager.GetString("PropertyDesc_OtherCollider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Joint... ähnelt.
        /// </summary>
        public static string PropertyName_AddJoint {
            get {
                return ResourceManager.GetString("PropertyName_AddJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Collider ähnelt.
        /// </summary>
        public static string PropertyName_OtherCollider {
            get {
                return ResourceManager.GetString("PropertyName_OtherCollider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RigidBody ähnelt.
        /// </summary>
        public static string RigidBodyCamViewState_SelBodyName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Circle Shape ähnelt.
        /// </summary>
        public static string RigidBodyCamViewState_SelCircleShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelCircleShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop Shape ähnelt.
        /// </summary>
        public static string RigidBodyCamViewState_SelLoopShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelLoopShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polygon Shape ähnelt.
        /// </summary>
        public static string RigidBodyCamViewState_SelPolyShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelPolyShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shape ähnelt.
        /// </summary>
        public static string RigidBodyCamViewState_SelShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create {0} ähnelt.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create {0} Joints ähnelt.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyJointMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Source {0} ähnelt.
        /// </summary>
        public static string UndoRedo_CreateSoundEmitterSource {
            get {
                return ResourceManager.GetString("UndoRedo_CreateSoundEmitterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create {0} Sources ähnelt.
        /// </summary>
        public static string UndoRedo_CreateSoundEmitterSourceMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateSoundEmitterSourceMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete {0} Objects ähnelt.
        /// </summary>
        public static string UndoRedo_DeleteObjects {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete {0} ähnelt.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete {0} Joints ähnelt.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyJointMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Source {0} ähnelt.
        /// </summary>
        public static string UndoRedo_DeleteSoundEmitterSource {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteSoundEmitterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete {0} Sources ähnelt.
        /// </summary>
        public static string UndoRedo_DeleteSoundEmitterSourceMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteSoundEmitterSourceMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reparent {0} ähnelt.
        /// </summary>
        public static string UndoRedo_ReparentRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_ReparentRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reparent {0} Joints ähnelt.
        /// </summary>
        public static string UndoRedo_ReparentRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ReparentRigidBodyJointMulti", resourceCulture);
            }
        }
    }
}
