//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duality.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duality.Editor.Properties.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_redo {
            get {
                object obj = ResourceManager.GetObject("arrow_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_undo {
            get {
                object obj = ResourceManager.GetObject("arrow_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Advanced.
        /// </summary>
        public static string Category_Advanced {
            get {
                return ResourceManager.GetString("Category_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Diagnostics.
        /// </summary>
        public static string Category_Diagnostics {
            get {
                return ResourceManager.GetString("Category_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a General.
        /// </summary>
        public static string Category_General {
            get {
                return ResourceManager.GetString("Category_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Graphics.
        /// </summary>
        public static string Category_Graphics {
            get {
                return ResourceManager.GetString("Category_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Physics.
        /// </summary>
        public static string Category_Physics {
            get {
                return ResourceManager.GetString("Category_Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sound.
        /// </summary>
        public static string Category_Sound {
            get {
                return ResourceManager.GetString("Category_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ColorPick {
            get {
                object obj = ResourceManager.GetObject("ColorPick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ColorWheel {
            get {
                object obj = ResourceManager.GetObject("ColorWheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrow {
            get {
                object obj = ResourceManager.GetObject("CursorArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowAction {
            get {
                object obj = ResourceManager.GetObject("CursorArrowAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowActionMove {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowActionRotate {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionRotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowActionScale {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorHandGrab {
            get {
                object obj = ResourceManager.GetObject("CursorHandGrab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorHandGrabbing {
            get {
                object obj = ResourceManager.GetObject("CursorHandGrabbing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;UserData&gt;
        ///  &lt;EditorApp&gt;
        ///    &lt;Backups&gt;true&lt;/Backups&gt;
        ///    &lt;Autosaves&gt;ThirtyMinutes&lt;/Autosaves&gt;
        ///    &lt;FirstSession&gt;true&lt;/FirstSession&gt;
        ///  &lt;/EditorApp&gt;
        ///  &lt;Plugins&gt;
        ///    &lt;Plugin id=&quot;CamView&quot;&gt;
        ///      &lt;CamView id=&quot;0&quot;&gt;
        ///        &lt;Perspective&gt;Parallax&lt;/Perspective&gt;
        ///        &lt;FocusDist&gt;500&lt;/FocusDist&gt;
        ///        &lt;BackgroundColor&gt;
        ///          &lt;R&gt;64&lt;/R&gt;
        ///          &lt;G&gt;64&lt;/G&gt;
        ///          &lt;B&gt;64&lt;/B&gt;
        ///          &lt;A&gt;0&lt;/A&gt;
        ///        &lt;/BackgroundColor&gt;
        ///        &lt;SnapToGridSize&gt;
        ///           [stringa troncata]&quot;;.
        /// </summary>
        public static string DefaultEditorUserData {
            get {
                return ResourceManager.GetString("DefaultEditorUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dualitor.
        /// </summary>
        public static string EditorApplicationTitle {
            get {
                return ResourceManager.GetString("EditorApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///using Duality;
        ///using Duality.Serialization;
        ///
        ///namespace ROOTNAMESPACE.ErrorHandlers
        ///{
        ///	public class NewProjectErrorHandler : SerializeErrorHandler
        ///	{
        ///		public override void HandleError(SerializeError error)
        ///		{
        ///			ResolveTypeError resolveTypeError = error as ResolveTypeError;
        ///			if (resolveTypeError != null)
        ///			{
        ///				string fixedTypeId = resolveTypeError.TypeId;
        ///
        ///				if (fixedTypeId.StartsWith(&quot;OLDROOTNA [stringa troncata]&quot;;.
        /// </summary>
        public static string ErrorHandlersTemplate {
            get {
                return ResourceManager.GetString("ErrorHandlersTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        public static byte[] GamePluginTemplate {
            get {
                object obj = ResourceManager.GetObject("GamePluginTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a /*
        /// * A set of static helper classes that provide easy runtime access to the games resources.
        /// * This file is auto-generated. Any changes made to it are lost as soon as Duality decides
        /// * to regenerate it.
        /// */
        ///namespace GameRes
        ///{
        ///CONTENT
        ///}
        ///.
        /// </summary>
        public static string GameResTemplate {
            get {
                return ResourceManager.GetString("GameResTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No information available..
        /// </summary>
        public static string HelpInfo_NotAvailable_Desc {
            get {
                return ResourceManager.GetString("HelpInfo_NotAvailable_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconClass {
            get {
                object obj = ResourceManager.GetObject("IconClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        /// </summary>
        public static System.Drawing.Icon IconCog {
            get {
                object obj = ResourceManager.GetObject("IconCog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconNamespace {
            get {
                object obj = ResourceManager.GetObject("IconNamespace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        /// </summary>
        public static System.Drawing.Icon IconWorkingFolder {
            get {
                object obj = ResourceManager.GetObject("IconWorkingFolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageAppCreate {
            get {
                object obj = ResourceManager.GetObject("ImageAppCreate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageTemplateCurrent {
            get {
                object obj = ResourceManager.GetObject("ImageTemplateCurrent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageTemplateEmpty {
            get {
                object obj = ResourceManager.GetObject("ImageTemplateEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This is the first time you are starting Duality. By using it, you are agreeing to its license terms, as linked below..
        /// </summary>
        public static string LicenseAcceptDialog_FirstStartGeneric {
            get {
                return ResourceManager.GetString("LicenseAcceptDialog_FirstStartGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installing package {0} requires a license agreement..
        /// </summary>
        public static string LicenseAcceptDialog_PackageDesc {
            get {
                return ResourceManager.GetString("LicenseAcceptDialog_PackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a License text transcript unavailable. Check the License Url link below for the original license text source..
        /// </summary>
        public static string LicenseAcceptDialog_TranscriptUnavailable {
            get {
                return ResourceManager.GetString("LicenseAcceptDialog_TranscriptUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select which launcher application should be used for external game tests. By default, the Duality Launcher is used..
        /// </summary>
        public static string MenuItemInfo_ConfigureLauncher {
            get {
                return ResourceManager.GetString("MenuItemInfo_ConfigureLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If you&apos;re using a professional version of Visual Studio, this action will run the Duality launcher and trigger a debug event that allows you to attach the debugger to your game before anything happens. You can achieve the same by clicking the &quot;Run&quot; button of your Core Plugin in Visual Studio itself..
        /// </summary>
        public static string MenuItemInfo_DebugGame {
            get {
                return ResourceManager.GetString("MenuItemInfo_DebugGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duality always works locally in a project folder. The New Project dialog will help you set up a new one..
        /// </summary>
        public static string MenuItemInfo_NewProject {
            get {
                return ResourceManager.GetString("MenuItemInfo_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The project source code is where your game logic happens. To help you get started, Duality will create and open a suitable Visual Studio solution for you..
        /// </summary>
        public static string MenuItemInfo_OpenProjectSource {
            get {
                return ResourceManager.GetString("MenuItemInfo_OpenProjectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Runs the game in profiling mode without VSync or any other frame rate limiting mechanism..
        /// </summary>
        public static string MenuItemInfo_ProfileGame {
            get {
                return ResourceManager.GetString("MenuItemInfo_ProfileGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creates a version of the game ready to distribute to others, with all necessary files.
        /// </summary>
        public static string MenuItemInfo_PublishGame {
            get {
                return ResourceManager.GetString("MenuItemInfo_PublishGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Want to see how your game looks like in its release version? This will save all project data and run the external Duality launcher..
        /// </summary>
        public static string MenuItemInfo_RunGame {
            get {
                return ResourceManager.GetString("MenuItemInfo_RunGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Increases the Sandboxes game speed. This will not cause it to update more often, but simulate a higher timestep in each update..
        /// </summary>
        public static string MenuItemInfo_SandboxFaster {
            get {
                return ResourceManager.GetString("MenuItemInfo_SandboxFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pausing the Sandbox will suspend any game updates. Until being unpaused, the Sandbox will behave as if it wasn&apos;t there..
        /// </summary>
        public static string MenuItemInfo_SandboxPause {
            get {
                return ResourceManager.GetString("MenuItemInfo_SandboxPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unlike &quot;Run Game&quot;, entering the Sandbox mode doesn&apos;t rely on the Duality Launcher and will instead run the game directly inside the editor. This allows you to test and debug your game in real time while at the same time providing full editing functionality. Note that you&apos;ll have to focus a Cam View in &quot;Game View&quot; mode in order to pass on keyboard and mouse input to the game..
        /// </summary>
        public static string MenuItemInfo_SandboxPlay {
            get {
                return ResourceManager.GetString("MenuItemInfo_SandboxPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decreases the Sandboxes game speed. This will not cause it to update less often, but simulate a lower timestep in each update..
        /// </summary>
        public static string MenuItemInfo_SandboxSlower {
            get {
                return ResourceManager.GetString("MenuItemInfo_SandboxSlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A Sandbox step will cause the game to advance exactly one standard frame..
        /// </summary>
        public static string MenuItemInfo_SandboxStep {
            get {
                return ResourceManager.GetString("MenuItemInfo_SandboxStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a When leaving the Sandbox mode, the current Scene will be reset to its original state..
        /// </summary>
        public static string MenuItemInfo_SandboxStop {
            get {
                return ResourceManager.GetString("MenuItemInfo_SandboxStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This will save all project data, i.e. all existing Resources. If you take a look at the Project View, you might notice that some Resources are written in italics - these are the ones that have been changed without being saved yet..
        /// </summary>
        public static string MenuItemInfo_SaveAll {
            get {
                return ResourceManager.GetString("MenuItemInfo_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This operation will load and re-save all existing Resources. Due to the serialization progress, all Resources will be guaranteed to use the same file format and to be up-to-date according to core plugin class definitions..
        /// </summary>
        public static string MenuItemInfo_SerializerUpdateAll {
            get {
                return ResourceManager.GetString("MenuItemInfo_SerializerUpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If active, Duality will backup each file before saving it..
        /// </summary>
        public static string MenuItemInfo_ToggleBackups {
            get {
                return ResourceManager.GetString("MenuItemInfo_ToggleBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        public static string MenuItemName_About {
            get {
                return ResourceManager.GetString("MenuItemName_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Launcher....
        /// </summary>
        public static string MenuItemName_ConfigureLauncher {
            get {
                return ResourceManager.GetString("MenuItemName_ConfigureLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Project....
        /// </summary>
        public static string MenuItemName_NewProject {
            get {
                return ResourceManager.GetString("MenuItemName_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile Game.
        /// </summary>
        public static string MenuItemName_ProfileGame {
            get {
                return ResourceManager.GetString("MenuItemName_ProfileGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Publish Game.
        /// </summary>
        public static string MenuItemName_PublishGame {
            get {
                return ResourceManager.GetString("MenuItemName_PublishGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quit.
        /// </summary>
        public static string MenuItemName_Quit {
            get {
                return ResourceManager.GetString("MenuItemName_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Redo: {0}.
        /// </summary>
        public static string MenuItemName_Redo {
            get {
                return ResourceManager.GetString("MenuItemName_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Redo.
        /// </summary>
        public static string MenuItemName_RedoEmpty {
            get {
                return ResourceManager.GetString("MenuItemName_RedoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Increase Speed.
        /// </summary>
        public static string MenuItemName_SandboxFaster {
            get {
                return ResourceManager.GetString("MenuItemName_SandboxFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decrease Speed.
        /// </summary>
        public static string MenuItemName_SandboxSlower {
            get {
                return ResourceManager.GetString("MenuItemName_SandboxSlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update All.
        /// </summary>
        public static string MenuItemName_SerializerUpdateAll {
            get {
                return ResourceManager.GetString("MenuItemName_SerializerUpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Undo: {0}.
        /// </summary>
        public static string MenuItemName_Undo {
            get {
                return ResourceManager.GetString("MenuItemName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Undo.
        /// </summary>
        public static string MenuItemName_UndoEmpty {
            get {
                return ResourceManager.GetString("MenuItemName_UndoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Getting Started.
        /// </summary>
        public static string MenuItemName_WelcomeDialog {
            get {
                return ResourceManager.GetString("MenuItemName_WelcomeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string MenuName_Edit {
            get {
                return ResourceManager.GetString("MenuName_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        public static string MenuName_File {
            get {
                return ResourceManager.GetString("MenuName_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Help.
        /// </summary>
        public static string MenuName_Help {
            get {
                return ResourceManager.GetString("MenuName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Run.
        /// </summary>
        public static string MenuName_Run {
            get {
                return ResourceManager.GetString("MenuName_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string MenuName_Settings {
            get {
                return ResourceManager.GetString("MenuName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tools.
        /// </summary>
        public static string MenuName_Tools {
            get {
                return ResourceManager.GetString("MenuName_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View.
        /// </summary>
        public static string MenuName_View {
            get {
                return ResourceManager.GetString("MenuName_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can&apos;t export Resource.
        /// </summary>
        public static string Msg_CantExport_Caption {
            get {
                return ResourceManager.GetString("Msg_CantExport_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can&apos;t export Resource &apos;{0}&apos;. None of the available importers is able to handle this Resource type..
        /// </summary>
        public static string Msg_CantExport_Text {
            get {
                return ResourceManager.GetString("Msg_CantExport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can&apos;t import file.
        /// </summary>
        public static string Msg_CantImport_Caption {
            get {
                return ResourceManager.GetString("Msg_CantImport_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can&apos;t import file &apos;{0}&apos;. None of the available importers is able to handle the files format..
        /// </summary>
        public static string Msg_CantImport_Text {
            get {
                return ResourceManager.GetString("Msg_CantImport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Break Prefab Link?.
        /// </summary>
        public static string Msg_ConfirmBreakPrefabLink_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmBreakPrefabLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This action will break the objects Prefab Link. Proceed?.
        /// </summary>
        public static string Msg_ConfirmBreakPrefabLink_Desc {
            get {
                return ResourceManager.GetString("Msg_ConfirmBreakPrefabLink_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete selected objects?.
        /// </summary>
        public static string Msg_ConfirmDeleteSelectedObjects_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteSelectedObjects_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you really want to delete the selected objects?.
        /// </summary>
        public static string Msg_ConfirmDeleteSelectedObjects_Text {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteSelectedObjects_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Really quit?.
        /// </summary>
        public static string Msg_ConfirmQuit_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you really want to quit?.
        /// </summary>
        public static string Msg_ConfirmQuit_Desc {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Really quit?.
        /// </summary>
        public static string Msg_ConfirmQuitUnsaved_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuitUnsaved_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The following Resources have been modified without saving:{0}Do you want to save them before exiting?.
        /// </summary>
        public static string Msg_ConfirmQuitUnsaved_Desc {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuitUnsaved_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [ and {0} more ].
        /// </summary>
        public static string Msg_ConfirmQuitUnsaved_Desc_More {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuitUnsaved_Desc_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reload Resource?.
        /// </summary>
        public static string Msg_ConfirmReloadResource_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmReloadResource_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The currently active Resource &apos;{0}&apos; has been modified externally. Do you want to reload it from file? Any unsaved changes might be lost..
        /// </summary>
        public static string Msg_ConfirmReloadResource_Text {
            get {
                return ResourceManager.GetString("Msg_ConfirmReloadResource_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Target Directory.
        /// </summary>
        public static string Msg_CreateProjectErrorNestedFolder_Caption {
            get {
                return ResourceManager.GetString("Msg_CreateProjectErrorNestedFolder_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The specified target folder is located within the current working directory. Please select one that is located elsewhere..
        /// </summary>
        public static string Msg_CreateProjectErrorNestedFolder_Desc {
            get {
                return ResourceManager.GetString("Msg_CreateProjectErrorNestedFolder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Target Directory.
        /// </summary>
        public static string Msg_CreateProjectErrorTargetExists_Caption {
            get {
                return ResourceManager.GetString("Msg_CreateProjectErrorTargetExists_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The specified target folder already exists and is not empty. Please select a different one..
        /// </summary>
        public static string Msg_CreateProjectErrorTargetExists_Desc {
            get {
                return ResourceManager.GetString("Msg_CreateProjectErrorTargetExists_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The specified target folder is conflicting with an existing file. Please select a different one..
        /// </summary>
        public static string Msg_CreateProjectErrorTargetIsFilePath_Desc {
            get {
                return ResourceManager.GetString("Msg_CreateProjectErrorTargetIsFilePath_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save current Scene?.
        /// </summary>
        public static string Msg_EnterSandboxUnsavedScene_Caption {
            get {
                return ResourceManager.GetString("Msg_EnterSandboxUnsavedScene_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You are about to enter Sandbox mode although the current Scene is temporary, so it won&apos;t be restored when leaving Sandbox mode. Do you want to make it restorable by saving it before?.
        /// </summary>
        public static string Msg_EnterSandboxUnsavedScene_Desc {
            get {
                return ResourceManager.GetString("Msg_EnterSandboxUnsavedScene_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error Creating Project.
        /// </summary>
        public static string Msg_ErrorCantCreateProject_Caption {
            get {
                return ResourceManager.GetString("Msg_ErrorCantCreateProject_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can&apos;t create a new project, because a error occurred : {1}{0}.
        /// </summary>
        public static string Msg_ErrorCantCreateProject_Desc {
            get {
                return ResourceManager.GetString("Msg_ErrorCantCreateProject_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to perform task.
        /// </summary>
        public static string Msg_ErrorPerformBigTask_Caption {
            get {
                return ResourceManager.GetString("Msg_ErrorPerformBigTask_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred while performing task &apos;{0}&apos;: {1}{2}.
        /// </summary>
        public static string Msg_ErrorPerformBigTask_Desc {
            get {
                return ResourceManager.GetString("Msg_ErrorPerformBigTask_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can&apos;t reload core plugin.
        /// </summary>
        public static string Msg_ErrorReloadCorePlugin_Caption {
            get {
                return ResourceManager.GetString("Msg_ErrorReloadCorePlugin_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred reloading Duality core plugins: {0}{1}.
        /// </summary>
        public static string Msg_ErrorReloadCorePlugin_Desc {
            get {
                return ResourceManager.GetString("Msg_ErrorReloadCorePlugin_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Overwrite file?.
        /// </summary>
        public static string Msg_ImportConfirmOverwrite_Caption {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmOverwrite_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This import operation would overwrite already imported Resources or already present source / media files. Do you want to continue?.
        /// </summary>
        public static string Msg_ImportConfirmOverwrite_Text {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmOverwrite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Install new Template?.
        /// </summary>
        public static string Msg_InstallNewTemplate_Caption {
            get {
                return ResourceManager.GetString("Msg_InstallNewTemplate_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Template you selected is not located inside your global Template directory. Do you wish to send it there for future usage?.
        /// </summary>
        public static string Msg_InstallNewTemplate_Desc {
            get {
                return ResourceManager.GetString("Msg_InstallNewTemplate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm Delete.
        /// </summary>
        public static string Msg_PublishConfirmDeleteTargetDir_Caption {
            get {
                return ResourceManager.GetString("Msg_PublishConfirmDeleteTargetDir_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The specified directory already contains a non-empty folder named &apos;{0}&apos;. Delete folder in order to proceed?.
        /// </summary>
        public static string Msg_PublishConfirmDeleteTargetDir_Desc {
            get {
                return ResourceManager.GetString("Msg_PublishConfirmDeleteTargetDir_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid Target Directory.
        /// </summary>
        public static string Msg_PublishProjectErrorNestedFolder_Caption {
            get {
                return ResourceManager.GetString("Msg_PublishProjectErrorNestedFolder_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The specified target folder is located within the current working directory. Please select one that is located elsewhere..
        /// </summary>
        public static string Msg_PublishProjectErrorNestedFolder_Desc {
            get {
                return ResourceManager.GetString("Msg_PublishProjectErrorNestedFolder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Package Install Canceled.
        /// </summary>
        public static string MsgLicenseNotAgreedAbort_Caption {
            get {
                return ResourceManager.GetString("MsgLicenseNotAgreedAbort_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The install operation was canceled. You can only install this package when agreeing to its license terms..
        /// </summary>
        public static string MsgLicenseNotAgreedAbort_Desc {
            get {
                return ResourceManager.GetString("MsgLicenseNotAgreedAbort_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project Templates (*.zip)|*.zip.
        /// </summary>
        public static string OpenTemplateDialog_Filters {
            get {
                return ResourceManager.GetString("OpenTemplateDialog_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Project Template...
        /// </summary>
        public static string OpenTemplateDialog_Title {
            get {
                return ResourceManager.GetString("OpenTemplateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} objects.
        /// </summary>
        public static string PropertyGrid_N_Objects {
            get {
                return ResourceManager.GetString("PropertyGrid_N_Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the folder in which a new project will be created below..
        /// </summary>
        public static string SelectNewProjectFolderDialog_Desc {
            get {
                return ResourceManager.GetString("SelectNewProjectFolderDialog_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reloading core plugins....
        /// </summary>
        public static string TaskBarOverlay_ReloadCorePlugin_Desc {
            get {
                return ResourceManager.GetString("TaskBarOverlay_ReloadCorePlugin_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Changing project data format....
        /// </summary>
        public static string TaskChangeDataFormat_Caption {
            get {
                return ResourceManager.GetString("TaskChangeDataFormat_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The project data format has been changed to {0}. Existing Resource files will be converted shortly..
        /// </summary>
        public static string TaskChangeDataFormat_Desc {
            get {
                return ResourceManager.GetString("TaskChangeDataFormat_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updating all Resources....
        /// </summary>
        public static string TaskFormatUpdateAll_Caption {
            get {
                return ResourceManager.GetString("TaskFormatUpdateAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All existing Resource files are being updated according to the current file format specifications..
        /// </summary>
        public static string TaskFormatUpdateAll_Desc {
            get {
                return ResourceManager.GetString("TaskFormatUpdateAll_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installing Packages....
        /// </summary>
        public static string TaskInstallPackages_Caption {
            get {
                return ResourceManager.GetString("TaskInstallPackages_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duality is installing some required packages. This may include downloading them from the central package repository..
        /// </summary>
        public static string TaskInstallPackages_Desc {
            get {
                return ResourceManager.GetString("TaskInstallPackages_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preparing operation....
        /// </summary>
        public static string TaskPrepareInfo {
            get {
                return ResourceManager.GetString("TaskPrepareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Relocating ContentRefs....
        /// </summary>
        public static string TaskRenameContentRefs_Caption {
            get {
                return ResourceManager.GetString("TaskRenameContentRefs_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One or more Resources have been moved or renamed. Duality is searching for references to these Resources in order to update them..
        /// </summary>
        public static string TaskRenameContentRefs_Desc {
            get {
                return ResourceManager.GetString("TaskRenameContentRefs_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creates a new project by cloning the current one..
        /// </summary>
        public static string Template_Current_Desc {
            get {
                return ResourceManager.GetString("Template_Current_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current Project.
        /// </summary>
        public static string Template_Current_Name {
            get {
                return ResourceManager.GetString("Template_Current_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A project without any content..
        /// </summary>
        public static string Template_Empty_Desc {
            get {
                return ResourceManager.GetString("Template_Empty_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Empty Project.
        /// </summary>
        public static string Template_Empty_Name {
            get {
                return ResourceManager.GetString("Template_Empty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apply {0}.
        /// </summary>
        public static string UndoRedo_ApplyToPrefab {
            get {
                return ResourceManager.GetString("UndoRedo_ApplyToPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apply  {0} GameObjects.
        /// </summary>
        public static string UndoRedo_ApplyToPrefabMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ApplyToPrefabMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unlink {0}.
        /// </summary>
        public static string UndoRedo_BreakPrefabLink {
            get {
                return ResourceManager.GetString("UndoRedo_BreakPrefabLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unlink  {0} GameObjects.
        /// </summary>
        public static string UndoRedo_BreakPrefabLinkMulti {
            get {
                return ResourceManager.GetString("UndoRedo_BreakPrefabLinkMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clone {0}.
        /// </summary>
        public static string UndoRedo_CloneGameObject {
            get {
                return ResourceManager.GetString("UndoRedo_CloneGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clone {0} GameObjects.
        /// </summary>
        public static string UndoRedo_CloneGameObjectMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CloneGameObjectMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create {0}.
        /// </summary>
        public static string UndoRedo_CreateComponent {
            get {
                return ResourceManager.GetString("UndoRedo_CreateComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create {0} Components.
        /// </summary>
        public static string UndoRedo_CreateComponentMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateComponentMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create {0}.
        /// </summary>
        public static string UndoRedo_CreateGameObject {
            get {
                return ResourceManager.GetString("UndoRedo_CreateGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create {0} GameObjects.
        /// </summary>
        public static string UndoRedo_CreateGameObjectMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateGameObjectMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete {0}.
        /// </summary>
        public static string UndoRedo_DeleteComponent {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete {0} Components.
        /// </summary>
        public static string UndoRedo_DeleteComponentMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteComponentMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete {0}.
        /// </summary>
        public static string UndoRedo_DeleteGameObject {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete {0} GameObjects.
        /// </summary>
        public static string UndoRedo_DeleteGameObjectMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteGameObjectMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit {0}.
        /// </summary>
        public static string UndoRedo_EditProperty {
            get {
                return ResourceManager.GetString("UndoRedo_EditProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Macro: {0} Actions.
        /// </summary>
        public static string UndoRedo_Macro {
            get {
                return ResourceManager.GetString("UndoRedo_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset {0}.
        /// </summary>
        public static string UndoRedo_ResetComponent {
            get {
                return ResourceManager.GetString("UndoRedo_ResetComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset {0} Components.
        /// </summary>
        public static string UndoRedo_ResetComponentMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ResetComponentMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Revert {0}.
        /// </summary>
        public static string UndoRedo_ResetGameObject {
            get {
                return ResourceManager.GetString("UndoRedo_ResetGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Revert {0} GameObjects.
        /// </summary>
        public static string UndoRedo_ResetGameObjectMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ResetGameObjectMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Re-Parent {0}.
        /// </summary>
        public static string UndoRedo_SetComponentParent {
            get {
                return ResourceManager.GetString("UndoRedo_SetComponentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Re-Parent {0} Components.
        /// </summary>
        public static string UndoRedo_SetComponentParentMulti {
            get {
                return ResourceManager.GetString("UndoRedo_SetComponentParentMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rename {0}.
        /// </summary>
        public static string UndoRedo_SetGameObjectName {
            get {
                return ResourceManager.GetString("UndoRedo_SetGameObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rename {0} GameObjects.
        /// </summary>
        public static string UndoRedo_SetGameObjectNameMulti {
            get {
                return ResourceManager.GetString("UndoRedo_SetGameObjectNameMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Re-Parent {0}.
        /// </summary>
        public static string UndoRedo_SetGameObjectParent {
            get {
                return ResourceManager.GetString("UndoRedo_SetGameObjectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Re-Parent {0} GameObjects.
        /// </summary>
        public static string UndoRedo_SetGameObjectParentMulti {
            get {
                return ResourceManager.GetString("UndoRedo_SetGameObjectParentMulti", resourceCulture);
            }
        }
    }
}
