//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duality.Editor.Plugins.CamView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CamViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CamViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duality.Editor.Plugins.CamView.Properties.CamViewRes", typeof(CamViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string CamView_Action_Move {
            get {
                return ResourceManager.GetString("CamView_Action_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string CamView_Action_Rotate {
            get {
                return ResourceManager.GetString("CamView_Action_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string CamView_Action_Scale {
            get {
                return ResourceManager.GetString("CamView_Action_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting....
        /// </summary>
        public static string CamView_Action_Select_Active {
            get {
                return ResourceManager.GetString("CamView_Action_Select_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Control Shortcuts.
        /// </summary>
        public static string CamView_Help_CamActions {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F to focus the world origin..
        /// </summary>
        public static string CamView_Help_CamActions_Focus {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mouse Wheel, Middle and Right Mouse button to move..
        /// </summary>
        public static string CamView_Help_CamActions_Move {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Space for alternative camera movement..
        /// </summary>
        public static string CamView_Help_CamActions_MoveAlternate {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_MoveAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl + Arrow Keys, Add or Subtract to move by a fixed step..
        /// </summary>
        public static string CamView_Help_CamActions_MoveStep {
            get {
                return ResourceManager.GetString("CamView_Help_CamActions_MoveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Action Shortcuts.
        /// </summary>
        public static string CamView_Help_ObjActions {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift to limit an action to one axis..
        /// </summary>
        public static string CamView_Help_ObjActions_AxisLock {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_AxisLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl + C to clone the selected objects..
        /// </summary>
        public static string CamView_Help_ObjActions_Clone {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Delete to remove the selected objects..
        /// </summary>
        public static string CamView_Help_ObjActions_Delete {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Alt to perform an action on a clone of the current selection..
        /// </summary>
        public static string CamView_Help_ObjActions_EditClone {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_EditClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F to focus on the current selection..
        /// </summary>
        public static string CamView_Help_ObjActions_Focus {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Arrow Keys, Add or Subtract to move the selected objects by a fixed step..
        /// </summary>
        public static string CamView_Help_ObjActions_MoveStep {
            get {
                return ResourceManager.GetString("CamView_Help_ObjActions_MoveStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle: {0:F}°.
        /// </summary>
        public static string CamView_Status_Angle {
            get {
                return ResourceManager.GetString("CamView_Status_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0:F}.
        /// </summary>
        public static string CamView_Status_PosX {
            get {
                return ResourceManager.GetString("CamView_Status_PosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y: {0:F}.
        /// </summary>
        public static string CamView_Status_PosY {
            get {
                return ResourceManager.GetString("CamView_Status_PosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z: {0:F}.
        /// </summary>
        public static string CamView_Status_PosZ {
            get {
                return ResourceManager.GetString("CamView_Status_PosZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fades out the actual scene rendering to improve Layer visibility.
        /// </summary>
        public static string CamViewLayer_BackPlate_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_BackPlate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Plate.
        /// </summary>
        public static string CamViewLayer_BackPlate_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_BackPlate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a uniform spatial grid.
        /// </summary>
        public static string CamViewLayer_Grid_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_Grid_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string CamViewLayer_Grid_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_Grid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the physical constraints of a RigidBody Component.
        /// </summary>
        public static string CamViewLayer_RigidBodyJoint_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyJoint_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody Joints.
        /// </summary>
        public static string CamViewLayer_RigidBodyJoint_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyJoint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the physical shape of a RigidBody Component.
        /// </summary>
        public static string CamViewLayer_RigidBodyShape_Desc {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyShape_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody Shapes.
        /// </summary>
        public static string CamViewLayer_RigidBodyShape_Name {
            get {
                return ResourceManager.GetString("CamViewLayer_RigidBodyShape_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game View.
        /// </summary>
        public static string CamViewState_GameView_Name {
            get {
                return ResourceManager.GetString("CamViewState_GameView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody Editor.
        /// </summary>
        public static string CamViewState_RigidBodyEditor_Name {
            get {
                return ResourceManager.GetString("CamViewState_RigidBodyEditor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Editor.
        /// </summary>
        public static string CamViewState_SceneEditor_Name {
            get {
                return ResourceManager.GetString("CamViewState_SceneEditor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreateCircle {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreateCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreateEdge {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreateEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreateLoop {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreateLoop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowCreatePolygon {
            get {
                object obj = ResourceManager.GetObject("CursorArrowCreatePolygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CursorArrowEditVertices {
            get {
                object obj = ResourceManager.GetObject("CursorArrowEditVertices", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpCircleCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpCircleCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpEdgeCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpEdgeCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpEditVertices {
            get {
                object obj = ResourceManager.GetObject("IconCmpEditVertices", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpLoopCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpLoopCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCmpRectCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpRectCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconEye {
            get {
                object obj = ResourceManager.GetObject("IconEye", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconMonitor {
            get {
                object obj = ResourceManager.GetObject("IconMonitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconShapeSelect {
            get {
                object obj = ResourceManager.GetObject("IconShapeSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove {0} because it is required by the &apos;{1}&apos; Component..
        /// </summary>
        public static string MenuItemDesc_CantRemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemDesc_CantRemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Data.
        /// </summary>
        public static string MenuItemName_AppData {
            get {
                return ResourceManager.GetString("MenuItemName_AppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string MenuItemName_CamView {
            get {
                return ResourceManager.GetString("MenuItemName_CamView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MenuItemName_RemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemName_RemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string MenuItemName_ResetComponent {
            get {
                return ResourceManager.GetString("MenuItemName_ResetComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default User Data.
        /// </summary>
        public static string MenuItemName_UserData {
            get {
                return ResourceManager.GetString("MenuItemName_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Chain Shape.
        /// </summary>
        public static string RigidBodyCamViewState_ItemName_CreateChain {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_ItemName_CreateChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Circle Shape.
        /// </summary>
        public static string RigidBodyCamViewState_ItemName_CreateCircle {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_ItemName_CreateCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Loop Shape.
        /// </summary>
        public static string RigidBodyCamViewState_ItemName_CreateLoop {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_ItemName_CreateLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Polygon Shape.
        /// </summary>
        public static string RigidBodyCamViewState_ItemName_CreatePolygon {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_ItemName_CreatePolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select / Edit Shapes.
        /// </summary>
        public static string RigidBodyCamViewState_ItemName_EditShapes {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_ItemName_EditShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vertices.
        /// </summary>
        public static string RigidBodyCamViewState_ItemName_EditVertices {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_ItemName_EditVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody.
        /// </summary>
        public static string RigidBodyCamViewState_SelBodyName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelCircleShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelCircleShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelLoopShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelLoopShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelPolyShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelPolyShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyShape {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Shapes.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyShapeMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyShapeMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Vertex.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyShapeVertex {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyShapeVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyShape {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Shapes.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyShapeMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyShapeMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Vertex.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyShapeVertex {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyShapeVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0}.
        /// </summary>
        public static string UndoRedo_DropGameObjectInScene {
            get {
                return ResourceManager.GetString("UndoRedo_DropGameObjectInScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop {0} GameObjects.
        /// </summary>
        public static string UndoRedo_DropGameObjectInSceneMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DropGameObjectInSceneMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0}.
        /// </summary>
        public static string UndoRedo_MoveCamViewObj {
            get {
                return ResourceManager.GetString("UndoRedo_MoveCamViewObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} Objects.
        /// </summary>
        public static string UndoRedo_MoveCamViewObjMulti {
            get {
                return ResourceManager.GetString("UndoRedo_MoveCamViewObjMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Vertex.
        /// </summary>
        public static string UndoRedo_MoveRigidBodyShapeVertex {
            get {
                return ResourceManager.GetString("UndoRedo_MoveRigidBodyShapeVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate {0}.
        /// </summary>
        public static string UndoRedo_RotateCamViewObj {
            get {
                return ResourceManager.GetString("UndoRedo_RotateCamViewObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate {0} Objects.
        /// </summary>
        public static string UndoRedo_RotateCamViewObjMulti {
            get {
                return ResourceManager.GetString("UndoRedo_RotateCamViewObjMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale {0}.
        /// </summary>
        public static string UndoRedo_ScaleCamViewObj {
            get {
                return ResourceManager.GetString("UndoRedo_ScaleCamViewObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale {0} Objects.
        /// </summary>
        public static string UndoRedo_ScaleCamViewObjMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ScaleCamViewObjMulti", resourceCulture);
            }
        }
    }
}
