//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duality.Editor.Plugins.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorBaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorBaseRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duality.Editor.Plugins.Base.Properties.EditorBaseRes", typeof(EditorBaseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Material Resource based on the Texture..
        /// </summary>
        public static string ActionDesc_CreateMaterial {
            get {
                return ResourceManager.GetString("ActionDesc_CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new ShaderProgram Resource based on Vertex- and Fragmentshaders..
        /// </summary>
        public static string ActionDesc_CreateShaderProgram {
            get {
                return ResourceManager.GetString("ActionDesc_CreateShaderProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Sound Resource based on the AudioData..
        /// </summary>
        public static string ActionDesc_CreateSound {
            get {
                return ResourceManager.GetString("ActionDesc_CreateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new Texture Resource based on the Pixmap..
        /// </summary>
        public static string ActionDesc_CreateTexture {
            get {
                return ResourceManager.GetString("ActionDesc_CreateTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2013 (Update 3) or newer is required..
        /// </summary>
        public static string ActionDesc_DownloadVisualStudio {
            get {
                return ResourceManager.GetString("ActionDesc_DownloadVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the Resource..
        /// </summary>
        public static string ActionDesc_ExportResource {
            get {
                return ResourceManager.GetString("ActionDesc_ExportResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Camera on GameObject..
        /// </summary>
        public static string ActionDesc_FocusGameObject {
            get {
                return ResourceManager.GetString("ActionDesc_FocusGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a GameObject by instantiating the Prefab..
        /// </summary>
        public static string ActionDesc_InstantiatePrefab {
            get {
                return ResourceManager.GetString("ActionDesc_InstantiatePrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Resource in external editor..
        /// </summary>
        public static string ActionDesc_OpenResourceExternal {
            get {
                return ResourceManager.GetString("ActionDesc_OpenResourceExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Scene..
        /// </summary>
        public static string ActionDesc_OpenScene {
            get {
                return ResourceManager.GetString("ActionDesc_OpenScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports the Resource using the previously used source files..
        /// </summary>
        public static string ActionDesc_ReImportResource {
            get {
                return ResourceManager.GetString("ActionDesc_ReImportResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the Resource&apos;s source files in your file system..
        /// </summary>
        public static string ActionDesc_ShowResourceSources {
            get {
                return ResourceManager.GetString("ActionDesc_ShowResourceSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tutorial will guide you through your first steps with Duality..
        /// </summary>
        public static string ActionDesc_ViewGettingStartedTutorial {
            get {
                return ResourceManager.GetString("ActionDesc_ViewGettingStartedTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help? Ask a fellow forum user!.
        /// </summary>
        public static string ActionDesc_VisitCommunityForum {
            get {
                return ResourceManager.GetString("ActionDesc_VisitCommunityForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Material.
        /// </summary>
        public static string ActionName_CreateMaterial {
            get {
                return ResourceManager.GetString("ActionName_CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ShaderProgram.
        /// </summary>
        public static string ActionName_CreateShaderProgram {
            get {
                return ResourceManager.GetString("ActionName_CreateShaderProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Sound.
        /// </summary>
        public static string ActionName_CreateSound {
            get {
                return ResourceManager.GetString("ActionName_CreateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Texture.
        /// </summary>
        public static string ActionName_CreateTexture {
            get {
                return ResourceManager.GetString("ActionName_CreateTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Visual Studio.
        /// </summary>
        public static string ActionName_DownloadVisualStudio {
            get {
                return ResourceManager.GetString("ActionName_DownloadVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Resource.
        /// </summary>
        public static string ActionName_ExportResource {
            get {
                return ResourceManager.GetString("ActionName_ExportResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Resource.
        /// </summary>
        public static string ActionName_ReImportResource {
            get {
                return ResourceManager.GetString("ActionName_ReImportResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Source Files.
        /// </summary>
        public static string ActionName_ShowResourceSources {
            get {
                return ResourceManager.GetString("ActionName_ShowResourceSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started Tutorial.
        /// </summary>
        public static string ActionName_ViewGettingStartedTutorial {
            get {
                return ResourceManager.GetString("ActionName_ViewGettingStartedTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Community.
        /// </summary>
        public static string ActionName_VisitCommunityForum {
            get {
                return ResourceManager.GetString("ActionName_VisitCommunityForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DropdownSettingsBlack {
            get {
                object obj = ResourceManager.GetObject("DropdownSettingsBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconAbortCross {
            get {
                object obj = ResourceManager.GetObject("IconAbortCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconCommunity {
            get {
                object obj = ResourceManager.GetObject("IconCommunity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconDownloadCodeIDE {
            get {
                object obj = ResourceManager.GetObject("IconDownloadCodeIDE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconEye {
            get {
                object obj = ResourceManager.GetObject("IconEye", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconSpeakerBlack {
            get {
                object obj = ResourceManager.GetObject("IconSpeakerBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconSpeakerWhite {
            get {
                object obj = ResourceManager.GetObject("IconSpeakerWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IconTutorial {
            get {
                object obj = ResourceManager.GetObject("IconTutorial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove {0} because it is required by the &apos;{1}&apos; Component..
        /// </summary>
        public static string MenuItemDesc_CantRemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemDesc_CantRemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Data.
        /// </summary>
        public static string MenuItemName_AppData {
            get {
                return ResourceManager.GetString("MenuItemName_AppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MenuItemName_RemoveComponent {
            get {
                return ResourceManager.GetString("MenuItemName_RemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string MenuItemName_ResetComponent {
            get {
                return ResourceManager.GetString("MenuItemName_ResetComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default User Data.
        /// </summary>
        public static string MenuItemName_UserData {
            get {
                return ResourceManager.GetString("MenuItemName_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a joint type and click the add button to add a new joint to the Collider.
        /// </summary>
        public static string PropertyDesc_AddJoint {
            get {
                return ResourceManager.GetString("PropertyDesc_AddJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The joints second Collider, i.e. the one that is connected to this one using the joint..
        /// </summary>
        public static string PropertyDesc_OtherCollider {
            get {
                return ResourceManager.GetString("PropertyDesc_OtherCollider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Joint....
        /// </summary>
        public static string PropertyName_AddJoint {
            get {
                return ResourceManager.GetString("PropertyName_AddJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Collider.
        /// </summary>
        public static string PropertyName_OtherCollider {
            get {
                return ResourceManager.GetString("PropertyName_OtherCollider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReferenceInput {
            get {
                object obj = ResourceManager.GetObject("ReferenceInput", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RigidBody.
        /// </summary>
        public static string RigidBodyCamViewState_SelBodyName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelCircleShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelCircleShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelLoopShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelLoopShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelPolyShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelPolyShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string RigidBodyCamViewState_SelShapeName {
            get {
                return ResourceManager.GetString("RigidBodyCamViewState_SelShapeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0}.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Joints.
        /// </summary>
        public static string UndoRedo_CreateRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateRigidBodyJointMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Source {0}.
        /// </summary>
        public static string UndoRedo_CreateSoundEmitterSource {
            get {
                return ResourceManager.GetString("UndoRedo_CreateSoundEmitterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Sources.
        /// </summary>
        public static string UndoRedo_CreateSoundEmitterSourceMulti {
            get {
                return ResourceManager.GetString("UndoRedo_CreateSoundEmitterSourceMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Objects.
        /// </summary>
        public static string UndoRedo_DeleteObjects {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Joints.
        /// </summary>
        public static string UndoRedo_DeleteRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteRigidBodyJointMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Source {0}.
        /// </summary>
        public static string UndoRedo_DeleteSoundEmitterSource {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteSoundEmitterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} Sources.
        /// </summary>
        public static string UndoRedo_DeleteSoundEmitterSourceMulti {
            get {
                return ResourceManager.GetString("UndoRedo_DeleteSoundEmitterSourceMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparent {0}.
        /// </summary>
        public static string UndoRedo_ReparentRigidBodyJoint {
            get {
                return ResourceManager.GetString("UndoRedo_ReparentRigidBodyJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparent {0} Joints.
        /// </summary>
        public static string UndoRedo_ReparentRigidBodyJointMulti {
            get {
                return ResourceManager.GetString("UndoRedo_ReparentRigidBodyJointMulti", resourceCulture);
            }
        }
    }
}
