//------------------------------------------------------------------------------
// <auto-generated>
//	 Dieser Code wurde von einem Tool generiert.
//	 Laufzeitversion:4.0.30319.18063
//
//	 Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//	 der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duality.Editor.Plugins.HelpAdvisor.Properties {
	using System;
	
	
	/// <summary>
	///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
	/// </summary>
	// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
	// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
	// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
	// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class HelpAdvisorRes {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal HelpAdvisorRes() {
		}
		
		/// <summary>
		///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duality.Editor.Plugins.HelpAdvisor.Properties.HelpAdvisorRes", typeof(HelpAdvisorRes).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
		///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die The Advisor will support you with context-based information about Duality. Press F1 at any time to access more information about the current topic. ähnelt.
		/// </summary>
		public static string HelpInfo_Advisor_Desc {
			get {
				return ResourceManager.GetString("HelpInfo_Advisor_Desc", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Advisor Window ähnelt.
		/// </summary>
		public static string HelpInfo_Advisor_Topic {
			get {
				return ResourceManager.GetString("HelpInfo_Advisor_Topic", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		/// </summary>
		public static System.Drawing.Bitmap IconHelp {
			get {
				object obj = ResourceManager.GetObject("IconHelp", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Advisor ähnelt.
		/// </summary>
		public static string MenuItemName_Advisor {
			get {
				return ResourceManager.GetString("MenuItemName_Advisor", resourceCulture);
			}
		}
	}
}
